services:
  mysql:
    ports:
      - "3306:3306"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf