services:
  mysql:
    ports:
      - "3306:3306"
    # Убираем healthcheck в development для быстрого старта
    healthcheck:
      disable: true

  backend:
    # Используем development конфигурацию opcache
    build:
      args:
        APP_ENV: development
    volumes:
      # Монтируем код в development для live reload
      - ./backend:/var/www
    environment:
      APP_ENV: development
      APP_DEBUG: "true"
      # Отключаем opcache в development для лучшей отладки
      OPCACHE_ENABLE: "0"
      # Включаем подробное логирование
      LOG_LEVEL: debug
    # Убираем healthcheck в development
    healthcheck:
      disable: true

  redis:
    ports:
      - "6379:6379"
    # Убираем healthcheck в development
    healthcheck:
      disable: true

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
      # API URL для development
      API_URL: http://localhost/api
      # Включаем hot reload
      NITRO_DEV: "true"
    # Убираем healthcheck в development
    healthcheck:
      disable: true

  nginx:
    ports:
      - "80:80"
    volumes:
      # Development конфигурация nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Монтируем статические файлы для development
      - ./backend/public:/var/www/backend/public:ro
      # Логи nginx для отладки
      - ./logs/nginx:/var/log/nginx
    # Убираем healthcheck в development
    healthcheck:
      disable: true