services:
  mysql:
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      API_URL: http://localhost:8000

  scheduler:
    volumes:
      - ./backend:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: "true"